[tool.poetry]
name = "spacy-ru"
version = "0.1.0"
description = ""
authors = ["Yuri Baburov <burchik@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
pymorphy2 = "^0.8"
notebook = "^5.6"
pandas = "^0.23.4"
nltk = "^3.3"
msgpack = "^0.5.6"
spacy = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipython = "^6.5"
#cupy-cuda91 = ">=4.3"
